---
title: "Data Visualization On Forest Fire Data"
author: "Himanshu Madan"
date: "26/09/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning = FALSE,message = FALSE)
```

```{r}
library(tidyverse)
data <- read_csv("forestfires.csv")
head(data)
```
```{r}
colnames(data)
```
```{r}
print("Months:")
data %>% pull(month) %>% unique
print("Days:")
data %>% pull(day) %>% unique

```
```{r}
month_order <- c("jan", "feb", "mar",
                 "apr", "may", "jun",
                 "jul", "aug", "sep",
                 "oct", "nov", "dec")
dow_order <- c("sun", "mon", "tue", "wed", "thu", "fri", "sat")
data <- data %>% 
  mutate(
    month = factor(month, levels = month_order),
    day = factor(day, levels = dow_order)
  )
```

```{r}
monthly_fires <- data %>% group_by(month) %>%
  summarise(
    total_fires = n()
  )

monthly_fires %>%
  ggplot(aes(x = month,y = total_fires)) + 
  geom_col() + 
  labs(
    title = "Number of forest fires in data by month",
    y = "Fire count",
    x = "Month"
  )
```

```{r}
daily_fires <- data %>% group_by(day) %>%
  summarise(
    total_fires = n()
  )

daily_fires %>%
  ggplot(aes(x = day,y = total_fires)) + 
  geom_col() + 
  labs(
    title = "Number of forest fires in data by day",
    y = "Fire count",
    x = "Day"
  )
```


```{r}
data_long <- data %>% 
  pivot_longer(
    cols = c("FFMC", "DMC", "DC", 
             "ISI", "temp", "RH", 
             "wind", "rain"),
    names_to = "data_col",
    values_to = "value"
  )
data_long %>% 
  ggplot(aes(x = month, y = value)) +
  geom_boxplot() +
  facet_wrap(vars(data_col), scale = "free_y") +
  labs(
    title = "Variable changes over month",
    x = "Month",
    y = "Variable value"
  )

```
```{r}
data_long %>% 
  filter(area < 300) %>% 
  ggplot(aes(x = value, y = area)) +
  geom_point() +
  facet_wrap(vars(data_col), scales = "free_x") +
  labs(
    title = "Relationships between other variables and area burned (area < 300)",
    x = "Value of column",
    y = "Area burned (hectare)"
  )
```

