---
title: "Covid-19 Virus Trends"
author: "Himanshu Madan"
date: "24/09/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning = FALSE,message = FALSE)
```

Importing the data (from Kaggle: https://www.kaggle.com/lin0li/covid19testing)

```{r}
library(readr)
covid_df <- read_csv("covid19.csv")
```


```{r}
dim(covid_df)
```
```{r}
vector_cols <- colnames(covid_df)
vector_cols
```

```{r}
head(covid_df)
```

```{r}
library(tibble)
glimpse(covid_df)
```

Removing rows having single states in province_state column
```{r}
library(dplyr)

covid_df_all_states <- covid_df %>% 
  filter(Province_State == "All States") %>% 
  select(-Province_State)
covid_df_all_states
```

We'll be focusing mainly on columns giving daily data.
```{r}
covid_df_all_states_daily <- covid_df_all_states %>%  select(Date, Country_Region, active, hospitalizedCurr, daily_tested, daily_positive)

head(covid_df_all_states_daily)
```


```{r}
covid_df_all_states_daily_sum <- covid_df_all_states_daily %>%  group_by(Country_Region) %>% 
summarize(tested = sum(daily_tested),
          positive = sum(daily_positive),
          active = sum(active),
          hospitalized = sum(hospitalizedCurr)) %>%
arrange(-tested)

covid_df_all_states_daily_sum
```


```{r}
covid_top_10 <- head(covid_df_all_states_daily_sum,10)
covid_top_10
```
Creating vectors
```{r}
countries <- covid_top_10$Country_Region
tested_cases <- covid_top_10$tested
positive_cases <- covid_top_10$positive
active_cases <- covid_top_10$active
hospitalized_cases <- covid_top_10$hospitalized
```

Naming Vectors
```{r}
names(positive_cases) <- countries
names(tested_cases) <- countries
names(active_cases) <- countries
names(hospitalized_cases) <- countries
```

```{r}
positive_cases
sum(positive_cases)
mean(positive_cases)
positive_cases/ sum(positive_cases)
```
```{r}
positive_cases / tested_cases
```

```{r}
positive_tested_top_3 <- c("United Kingdom" = 0.11, "United States" = 0.10, "Turkey" = 0.08)

```

```{r}
united_kingdom <- c(0.11, 1473672, 166909, 0, 0)
united_states <- c(0.10, 17282363, 1877179, 0, 0)
turkey <- c(0.08, 2031192, 163941, 2980960, 0)
```

```{r}
covid_matrix <- rbind(united_kingdom,united_states,turkey)
colnames(covid_matrix) <- c("Ratio", "tested", "positive", "active", "hospitalized")
covid_matrix
```
```{r}
question <- "Which countries have had the highest number of positive cases against the number of tests?"
answer <- c("Positive tested cases" = positive_tested_top_3)

```

```{r}
datasets <- list(
  original = covid_df,
  allstates = covid_df_all_states,
  daily = covid_df_all_states_daily,
  top_10 = covid_top_10
)
```

